name: Scala CI

on:
  push:
    branches: [ "base" ]
    tags: ["v*"]
  pull_request:
    branches: [ "base" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: coursier/cache-action@v6

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
                
    - name: Check format
      run: sbt scalafmtCheck     
        
    - name: Run tests
      run: sbt test

  publish:
    name: Publish Artifacts
    needs: [ build ]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/base' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'

      - uses: coursier/cache-action@v6

