on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
    
    - name: Generate token
      id: generate-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: 123456
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
        
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@v2
      with:
        # used for authoring updates:
        github-token: ${{ steps.generate-token.outputs.token }}
        author-email: 225513+evolution-scala-bot[bot]@users.noreply.github.com
        author-name: evolution-scala-bot[bot]
        github-app-id: 225513
        github-app-key: ${{ secrets.STEWARD_APP_PRIVATE_KEY }}
